# -*- coding: utf-8 -*-
"""
replay.py
=========
Aufzeichnung und Verwaltung von Spiel-Wiederholungen ("Replays").

Gespeichert wird in ``replay.json`` neben diesem Modul (bei einer mit
pyinstall.bat gebauten .exe: neben der .exe). Die Datei hat je Spiel eine
eigene Unterkategorie::

    {
      "_generated": "generated by PyGameZ at ... (YYYY-MM-DD HH:MM:SS)",
      "minigolf": [ {replay}, {replay}, ... ],
      "bowling":  [ {replay}, ... ]
    }

Aufgezeichnet werden nur Minigolf und Bowling - beides sind Spiele mit
kurzen, in sich abgeschlossenen Sequenzen (Schlag bzw. Wurf), die man sich
gern noch einmal anschaut. Ob überhaupt aufgezeichnet wird, steht in den
Einstellungen (``settings.json`` -> ``replay.enabled``); abschaltbar im
Willkommens-Screen beim ersten Start und jederzeit in den Optionen.

Wie ein Replay aussieht
-----------------------
Aufgezeichnet wird NICHT die Eingabe (Physik mit Zufall ließe sich nicht
exakt nachrechnen), sondern die tatsächliche BAHN der Objekte - Bild für
Bild in einem festen Zeitraster (``RATE`` Samples je Sekunde). Damit sieht
die Wiederholung immer genau so aus wie die gespielte Runde, auch wenn sich
die Physik in einer späteren Version ändert.

Ein Replay ist ein dict::

    {"v": 1,                       # Format-Version
     "id": "minigolf-2026...",     # eindeutig (zum Speichern/Löschen)
     "game": "minigolf",           # Spiel (= Unterkategorie)
     "date": "2026-08-29 14:12",   # Aufnahmezeitpunkt
     "title": "Tour 3",            # Kurzname für die Liste
     "sub":   "29 (-2)",           # Zweitzeile (fertiger Text)
     "rate": 30,                   # Samples je Sekunde
     "meta": {...},                # spielabhängige Kopfdaten
     "layouts": [...],             # optionale Kulissen (Minigolf: Bahnen)
     "scenes": [ {...}, ... ]}     # die Sequenzen (Schlag bzw. Wurf)

Jede Szene enthält ihre Kopfdaten (welche Bahn, welcher Spieler, welches
Ergebnis) und unter "f" die Samples: bei Minigolf eine flache Zahlenliste
(x, y, x, y, ...), bei Bowling je Sample eine Liste
[ball_x, ball_y, drehung, pin_i, x, y, gefallen, ...] - Pins stehen nur
darin, wenn sie sich seit dem letzten Sample bewegt haben (das spart bei
zehn Pins gut drei Viertel der Daten).

Verwendung im Spiel::

    self.rec = replay.recorder("minigolf", self.settings, meta={...})
    ...
    if self.rec: self.rec.scene(flat=True, hole=0, ...)   # Sequenz beginnt
    if self.rec: self.rec.tick(dt, self._rec_sample)      # je Frame
    if self.rec: self.rec.close(self._rec_sample, end="cup")
    ...
    self.replay = self.rec.result(title="...", sub="...")  # Rundenende
"""

import json
import os
import sys
import time

# Zeitraster der Aufnahme: 30 Samples je Sekunde. Feiner lohnt nicht (das
# Auge sieht es nicht), gröber ruckelt bei schnellen Bällen.
RATE = 30
STEP = 1.0 / RATE

# Format-Version der Dateistruktur (steht in jedem Replay).
VERSION = 1

# Spiele mit Aufzeichnung = die Unterkategorien in replay.json.
GAMES = ("minigolf", "bowling")

# Je Spiel höchstens so viele gespeicherte Replays (danach meldet
# save_replay() "voll" - gelöscht wird nur auf Wunsch im Replay-Screen).
MAX_PER_GAME = 20

# Sicherheitsnetz gegen Endlos-Partien: mehr Samples werden nicht
# aufgezeichnet, die Aufnahme wird dann still verworfen.
MAX_SAMPLES = 60000

# In einer PyInstaller-.exe (sys.frozen) zeigt __file__ in den temporären
# Entpack-Ordner, der beim Beenden verschwindet - dann neben der .exe.
if getattr(sys, "frozen", False):
    _DIR = os.path.dirname(sys.executable)
else:
    _DIR = os.path.dirname(os.path.abspath(__file__))
_PATH = os.path.join(_DIR, "replay.json")


# ---------------------------------------------------------------------------
#  Einstellung
# ---------------------------------------------------------------------------

def is_enabled(settings):
    """True, wenn der Replay-Modus in den Einstellungen an ist (Standard: an)."""
    if not isinstance(settings, dict):
        return True
    sect = settings.get("replay")
    if not isinstance(sect, dict):
        return True
    return bool(sect.get("enabled", True))


# ---------------------------------------------------------------------------
#  Datei lesen/schreiben
# ---------------------------------------------------------------------------

def _read_raw():
    """Liest replay.json roh (immer ein dict, leer bei Fehler/ohne Datei)."""
    try:
        with open(_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError, ValueError):
        return {}


def _write_raw(data):
    """Schreibt die ganze Datei zurück (Fehler werden bewusst ignoriert).

    "_generated" (Anlege-Datum) steht immer als erster Eintrag; ein bereits
    vorhandener Stempel bleibt erhalten. Gespeichert wird kompakt (ohne
    Einrückung) - Replays sind Rohdaten, keine Datei zum Handbearbeiten.
    """
    stamp = data.get("_generated")
    if not (isinstance(stamp, str) and stamp):
        stamp = ("generated by PyGameZ at " + time.strftime("%Y-%m-%d %H:%M:%S")
                 + " (YYYY-MM-DD HH:MM:SS)")
    out = {"_generated": stamp}
    for key in GAMES:
        items = data.get(key)
        if isinstance(items, list) and items:
            out[key] = items
    try:
        with open(_PATH, "w", encoding="utf-8") as f:
            json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
        return True
    except OSError:
        # Ohne Schreibrechte läuft alles weiter - nur eben ohne Archiv.
        return False


def _valid(rep):
    """Grobprüfung eines geladenen Replays (beschädigte werden übersprungen)."""
    return (isinstance(rep, dict) and isinstance(rep.get("scenes"), list)
            and rep["scenes"] and isinstance(rep.get("id"), str)
            and rep.get("game") in GAMES)


def load_game(game):
    """Alle gespeicherten Replays eines Spiels (neueste zuerst)."""
    items = _read_raw().get(game)
    if not isinstance(items, list):
        return []
    return [r for r in items if _valid(r)]


def load_all():
    """{spiel: [replay, ...]} für alle Spiele mit Aufzeichnung."""
    raw = _read_raw()
    out = {}
    for game in GAMES:
        items = raw.get(game)
        out[game] = [r for r in items if _valid(r)] if isinstance(items, list) else []
    return out


def count(game):
    """Anzahl gespeicherter Replays eines Spiels."""
    return len(load_game(game))


def is_full(game):
    """True, wenn das Archiv dieses Spiels voll ist (MAX_PER_GAME)."""
    return count(game) >= MAX_PER_GAME


def save_replay(rep):
    """Speichert ein Replay dauerhaft. Gibt (ok, grund) zurück.

    grund ist "" bei Erfolg, sonst "full" (Archiv voll), "invalid" oder
    "io" (Datei nicht schreibbar).
    """
    if not _valid(rep):
        return False, "invalid"
    game = rep["game"]
    data = _read_raw()
    items = data.get(game)
    if not isinstance(items, list):
        items = []
    items = [r for r in items if _valid(r) and r.get("id") != rep["id"]]
    if len(items) >= MAX_PER_GAME:
        return False, "full"
    items.insert(0, rep)          # neueste zuerst
    data[game] = items
    return (True, "") if _write_raw(data) else (False, "io")


def delete_replay(game, rep_id):
    """Löscht ein gespeichertes Replay. True, wenn etwas entfernt wurde."""
    data = _read_raw()
    items = data.get(game)
    if not isinstance(items, list):
        return False
    keep = [r for r in items if r.get("id") != rep_id]
    if len(keep) == len(items):
        return False
    data[game] = keep
    return _write_raw(data)


def is_saved(game, rep_id):
    """True, wenn ein Replay mit dieser id bereits im Archiv liegt."""
    return any(r.get("id") == rep_id for r in load_game(game))


def scene_len(scene):
    """Anzahl Samples einer Szene (flach gespeicherte zählen paarweise)."""
    f = scene.get("f")
    if not isinstance(f, list):
        return 0
    if scene.get("flat"):
        return len(f) // 2
    return len(f)


def duration(rep):
    """Spieldauer eines Replays in Sekunden (Summe aller Samples)."""
    rate = rep.get("rate") or RATE
    total = sum(scene_len(sc) for sc in rep.get("scenes", []))
    return total / float(rate)


def format_duration(seconds):
    """Sekunden -> "1:05" (sprachneutral, für Listen und die Leiste)."""
    seconds = max(0, int(seconds + 0.5))
    return "%d:%02d" % divmod(seconds, 60)


# ---------------------------------------------------------------------------
#  Aufnahme
# ---------------------------------------------------------------------------

class Recorder:
    """Sammelt die Bahnkurven einer Partie im Speicher.

    Die Spiele rufen nur vier Methoden: ``scene()`` beginnt eine Sequenz,
    ``tick()`` nimmt im festen Raster Samples, ``close()`` beendet sie und
    ``result()`` gibt am Rundenende das fertige Replay-dict zurück.

    Wächst eine Aufnahme über MAX_SAMPLES, schaltet sich der Recorder
    still ab (``self.dead``) - lieber kein Replay als eine 20-MB-Datei.
    """

    def __init__(self, game, meta=None):
        self.game = game
        self.meta = dict(meta or {})
        self.layouts = []
        self.scenes = []
        self.samples = 0
        self.dead = False
        self._scene = None
        self._acc = 0.0

    # ----- Kulissen (Minigolf: die Bahn) --------------------------------

    def layout(self, data):
        """Legt eine Kulisse ab und gibt ihren Index zurück (ohne Dubletten)."""
        if self.dead:
            return 0
        for i, known in enumerate(self.layouts):
            if known == data:
                return i
        self.layouts.append(data)
        return len(self.layouts) - 1

    # ----- Sequenzen -----------------------------------------------------

    def scene(self, flat=False, **info):
        """Beginnt eine Sequenz (Minigolf: ein Schlag, Bowling: ein Wurf)."""
        if self.dead:
            return
        self._scene = dict(info)
        self._scene["flat"] = bool(flat)
        self._scene["f"] = []
        self.scenes.append(self._scene)
        self._acc = STEP          # das erste Sample sofort nehmen

    def set(self, **info):
        """Trägt Kopfdaten in die laufende Sequenz nach (z.B. das Ergebnis)."""
        if self._scene is not None:
            self._scene.update(info)

    def set_last(self, **info):
        """Trägt Kopfdaten in die zuletzt begonnene Sequenz nach.

        Anders als ``set()`` funktioniert das auch, wenn die Sequenz bereits
        geschlossen ist - Minigolf schreibt so das Bahn-Ergebnis noch an den
        letzten Schlag, der die Bahn beendet hat.
        """
        if not self.dead and self.scenes:
            self.scenes[-1].update(info)

    def tick(self, dt, sample_fn):
        """Nimmt im Raster RATE Samples auf (je Frame einmal aufrufen).

        ``sample_fn`` liefert eine Liste/Tupel von Zahlen. Bei einer flachen
        Sequenz werden sie angehängt, sonst als eigenes Sample abgelegt.
        Läuft die Anzeige langsamer als RATE, entstehen mehrere gleiche
        Samples - die Wiedergabe hat dann dasselbe Timing wie das Original.
        """
        if self.dead or self._scene is None:
            return
        self._acc += dt
        while self._acc >= STEP:
            self._acc -= STEP
            self._emit(sample_fn())

    def _emit(self, values):
        if values is None:
            return
        sc = self._scene
        if sc["flat"]:
            sc["f"].extend(values)
        else:
            sc["f"].append(list(values))
        self.samples += 1
        if self.samples > MAX_SAMPLES:
            self.dead = True
            self.scenes = []
            self.layouts = []
            self._scene = None

    def close(self, sample_fn=None, **info):
        """Beendet die laufende Sequenz (mit einem letzten Sample)."""
        if self.dead or self._scene is None:
            return
        if sample_fn is not None:
            self._emit(sample_fn())
        if self._scene is not None:
            self._scene.update(info)
        self._scene = None

    def drop_where(self, **match):
        """Wirft Sequenzen weg, deren Kopfdaten alle Vorgaben erfüllen.

        Gebraucht beim Bahn-Neustart in Minigolf (Taste F): die Schläge der
        abgebrochenen Bahn sollen nicht im Replay landen.
        """
        if self.dead:
            return
        keep = []
        for sc in self.scenes:
            if all(sc.get(k) == v for k, v in match.items()):
                self.samples -= scene_len(sc)
                continue
            keep.append(sc)
        self.scenes = keep
        self._scene = None

    # ----- Abschluss ------------------------------------------------------

    def result(self, title="", sub="", **meta):
        """Baut das fertige Replay-dict (oder None, wenn nichts brauchbar ist)."""
        if self.dead:
            return None
        scenes = [sc for sc in self.scenes if scene_len(sc) > 0]
        if not scenes:
            return None
        self.meta.update(meta)
        rep = {"v": VERSION,
               "id": "%s-%s-%d" % (self.game, time.strftime("%Y%m%d%H%M%S"),
                                   len(scenes)),
               "game": self.game,
               "date": time.strftime("%Y-%m-%d %H:%M"),
               "title": title,
               "sub": sub,
               "rate": RATE,
               "meta": self.meta,
               "scenes": scenes}
        if self.layouts:
            rep["layouts"] = self.layouts
        return rep


def recorder(game, settings=None, meta=None):
    """Erzeugt einen Recorder - oder None, wenn Replays abgeschaltet sind."""
    if game not in GAMES:
        return None
    if settings is not None and not is_enabled(settings):
        return None
    return Recorder(game, meta)
