# -*- coding: utf-8 -*-
"""
replay.py
=========
Aufzeichnung und Verwaltung von Spiel-Wiederholungen ("Replays").

Gespeichert wird in ``replay.json`` neben diesem Modul (bei einer mit
pyinstall.bat gebauten .exe: neben der .exe). Die Datei hat je Spiel eine
eigene Unterkategorie::

    {
      "_generated": "generated by PyGameZ at ... (YYYY-MM-DD HH:MM:SS)",
      "minigolf": [ {replay}, {replay}, ... ],
      "bowling":  [ {replay}, ... ]
    }

Aufgezeichnet werden sechs Spiele::

    minigolf   je Szene ein Schlag
    bowling    je Szene ein Wurf
    billiard   je Szene ein Stoß
    pinball    je Szene ein Ball (Kugel 1 von 3)
    snake      je Szene ein Abschnitt (zwischen zwei Äpfeln)
    tetris     je Szene ein Abschnitt (zwischen zwei Level-/Zeilen-Marken)

Die ersten vier haben von Natur aus kurze, in sich abgeschlossene Sequenzen;
bei Snake und Tetris läuft die Partie durch - dort dient die Szene als
Kapitel (Schlüsselbild + Deltas), damit das Spulen schnell bleibt und die
Fortschrittsleiste Marken bekommt. Ob überhaupt aufgezeichnet wird, steht in
den Einstellungen (``settings.json`` -> ``replay.enabled``); abschaltbar im
Willkommens-Screen beim ersten Start und jederzeit in den Optionen.

Wie ein Replay aussieht
-----------------------
Aufgezeichnet wird NICHT die Eingabe (Physik mit Zufall ließe sich nicht
exakt nachrechnen), sondern die tatsächliche BAHN der Objekte - Bild für
Bild in einem festen Zeitraster (``RATE`` Samples je Sekunde). Damit sieht
die Wiederholung immer genau so aus wie die gespielte Runde, auch wenn sich
die Physik in einer späteren Version ändert.

Ein Replay ist ein dict::

    {"v": 1,                       # Format-Version
     "id": "minigolf-2026...",     # eindeutig (zum Speichern/Löschen)
     "game": "minigolf",           # Spiel (= Unterkategorie)
     "date": "2026-08-29 14:12",   # Aufnahmezeitpunkt
     "title": "Tour 3",            # Kurzname für die Liste
     "sub":   "29 (-2)",           # Zweitzeile (fertiger Text)
     "rate": 30,                   # Samples je Sekunde
     "meta": {...},                # spielabhängige Kopfdaten
     "layouts": [...],             # optionale Kulissen (Minigolf: Bahnen)
     "scenes": [ {...}, ... ]}     # die Sequenzen (Schlag bzw. Wurf)

Jede Szene enthält ihre Kopfdaten (welche Bahn, welcher Spieler, welches
Ergebnis) und unter "f" die Samples: bei Minigolf eine flache Zahlenliste
(x, y, x, y, ...), bei Bowling je Sample eine Liste
[ball_x, ball_y, drehung, pin_i, x, y, gefallen, ...] - Pins stehen nur
darin, wenn sie sich seit dem letzten Sample bewegt haben (das spart bei
zehn Pins gut drei Viertel der Daten).

Verwendung im Spiel::

    self.rec = replay.recorder("minigolf", self.settings, meta={...})
    ...
    if self.rec: self.rec.scene(flat=True, hole=0, ...)   # Sequenz beginnt
    if self.rec: self.rec.tick(dt, self._rec_sample)      # je Frame
    if self.rec: self.rec.close(self._rec_sample, end="cup")
    ...
    self.replay = self.rec.result(title="...", sub="...")  # Rundenende

Teilen
------
Ein Replay lässt sich als einzelne Datei weitergeben - Endung
``.lamapgzreplay``, aufgebaut wie die Bahn-/Level-Dateien in ugc.py::

    {"format": "pygamez.replay", "v": 1, "app": "PyGameZ",
     "exported": "2026-09-17 20:10", "replay": { ...das Replay-dict... }}

``export_to()`` schreibt so eine Datei, ``import_from()`` liest sie wieder
ein und legt sie ins Archiv (mit neuer id, falls die alte schon vergeben
ist). Beim Import wird auch ``.json`` angenommen; ein importiertes Replay
trägt ``"src": "file"`` und bekommt im Archiv ein kleines Import-Zeichen.
"""

import json
import os
import sys
import time

# Zeitraster der Aufnahme: 30 Samples je Sekunde. Feiner lohnt nicht (das
# Auge sieht es nicht), gröber ruckelt bei schnellen Bällen.
RATE = 30
STEP = 1.0 / RATE

# Format-Version der Dateistruktur (steht in jedem Replay).
VERSION = 1

# Spiele mit Aufzeichnung = die Unterkategorien in replay.json (Reihenfolge =
# Reiterleiste im Replay-Screen).
GAMES = ("minigolf", "bowling", "billiard", "pinball", "snake", "tetris")

# Endung einer geteilten Aufnahme. Beim Import wird auch ".json" genommen.
EXT = ".lamapgzreplay"
IMPORT_EXTS = (EXT, ".json")

# Kennung im Dateikopf - daran erkennt der Import, dass es ein Replay ist.
FORMAT = "pygamez.replay"

# Je Spiel höchstens so viele gespeicherte Replays (danach meldet
# save_replay() "voll" - gelöscht wird nur auf Wunsch im Replay-Screen).
MAX_PER_GAME = 20

# Sicherheitsnetz gegen Endlos-Partien: mehr Samples (bzw. mehr einzelne
# Zahlen) werden nicht aufgezeichnet. Die Aufnahme bricht dann ab und trägt
# "capped" - der Replay-Screen weist darauf hin. 60000 Samples sind bei
# 30 Samples/s gut eine halbe Stunde; die Zahlengrenze greift nur bei sehr
# vollen Bildern (Pinball-Multiball, langer Snake-Körper).
MAX_SAMPLES = 60000
MAX_VALUES = 420000

# In einer PyInstaller-.exe (sys.frozen) zeigt __file__ in den temporären
# Entpack-Ordner, der beim Beenden verschwindet - dann neben der .exe.
if getattr(sys, "frozen", False):
    _DIR = os.path.dirname(sys.executable)
else:
    _DIR = os.path.dirname(os.path.abspath(__file__))
_PATH = os.path.join(_DIR, "replay.json")


# ---------------------------------------------------------------------------
#  Einstellung
# ---------------------------------------------------------------------------

def is_enabled(settings):
    """True, wenn der Replay-Modus in den Einstellungen an ist (Standard: an)."""
    if not isinstance(settings, dict):
        return True
    sect = settings.get("replay")
    if not isinstance(sect, dict):
        return True
    return bool(sect.get("enabled", True))


# ---------------------------------------------------------------------------
#  Datei lesen/schreiben
# ---------------------------------------------------------------------------

def _read_raw():
    """Liest replay.json roh (immer ein dict, leer bei Fehler/ohne Datei)."""
    try:
        with open(_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError, ValueError):
        return {}


def _write_raw(data):
    """Schreibt die ganze Datei zurück (Fehler werden bewusst ignoriert).

    "_generated" (Anlege-Datum) steht immer als erster Eintrag; ein bereits
    vorhandener Stempel bleibt erhalten. Gespeichert wird kompakt (ohne
    Einrückung) - Replays sind Rohdaten, keine Datei zum Handbearbeiten.
    """
    stamp = data.get("_generated")
    if not (isinstance(stamp, str) and stamp):
        stamp = ("generated by PyGameZ at " + time.strftime("%Y-%m-%d %H:%M:%S")
                 + " (YYYY-MM-DD HH:MM:SS)")
    out = {"_generated": stamp}
    for key in GAMES:
        items = data.get(key)
        if isinstance(items, list) and items:
            out[key] = items
    try:
        with open(_PATH, "w", encoding="utf-8") as f:
            json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
        return True
    except OSError:
        # Ohne Schreibrechte läuft alles weiter - nur eben ohne Archiv.
        return False


def _valid(rep):
    """Grobprüfung eines geladenen Replays (beschädigte werden übersprungen)."""
    return (isinstance(rep, dict) and isinstance(rep.get("scenes"), list)
            and rep["scenes"] and isinstance(rep.get("id"), str)
            and rep.get("game") in GAMES)


def load_game(game):
    """Alle gespeicherten Replays eines Spiels (neueste zuerst)."""
    items = _read_raw().get(game)
    if not isinstance(items, list):
        return []
    return [r for r in items if _valid(r)]


def load_all():
    """{spiel: [replay, ...]} für alle Spiele mit Aufzeichnung."""
    raw = _read_raw()
    out = {}
    for game in GAMES:
        items = raw.get(game)
        out[game] = [r for r in items if _valid(r)] if isinstance(items, list) else []
    return out


def count(game):
    """Anzahl gespeicherter Replays eines Spiels."""
    return len(load_game(game))


def is_full(game):
    """True, wenn das Archiv dieses Spiels voll ist (MAX_PER_GAME)."""
    return count(game) >= MAX_PER_GAME


def save_replay(rep):
    """Speichert ein Replay dauerhaft. Gibt (ok, grund) zurück.

    grund ist "" bei Erfolg, sonst "full" (Archiv voll), "invalid" oder
    "io" (Datei nicht schreibbar).
    """
    if not _valid(rep):
        return False, "invalid"
    game = rep["game"]
    data = _read_raw()
    items = data.get(game)
    if not isinstance(items, list):
        items = []
    items = [r for r in items if _valid(r) and r.get("id") != rep["id"]]
    if len(items) >= MAX_PER_GAME:
        return False, "full"
    items.insert(0, rep)          # neueste zuerst
    data[game] = items
    return (True, "") if _write_raw(data) else (False, "io")


def delete_replay(game, rep_id):
    """Löscht ein gespeichertes Replay. True, wenn etwas entfernt wurde."""
    data = _read_raw()
    items = data.get(game)
    if not isinstance(items, list):
        return False
    keep = [r for r in items if r.get("id") != rep_id]
    if len(keep) == len(items):
        return False
    data[game] = keep
    return _write_raw(data)


def is_saved(game, rep_id):
    """True, wenn ein Replay mit dieser id bereits im Archiv liegt."""
    return any(r.get("id") == rep_id for r in load_game(game))


def unique_id(wanted, game):
    """Freie id im Archiv: hängt notfalls "-2", "-3" ... an (wie in ugc.py)."""
    wanted = str(wanted or game or "replay")
    if not is_saved(game, wanted):
        return wanted
    for n in range(2, 1000):
        cand = "%s-%d" % (wanted, n)
        if not is_saved(game, cand):
            return cand
    return wanted + "-" + time.strftime("%H%M%S")


# ---------------------------------------------------------------------------
#  Teilen: Export / Import (.lamapgzreplay)
# ---------------------------------------------------------------------------

def default_filename(rep):
    """Vorgeschlagener Dateiname beim Teilen: die id plus Endung."""
    base = str((rep or {}).get("id") or (rep or {}).get("game") or "replay")
    keep = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"
    base = "".join(c if c in keep else "-" for c in base)[:60] or "replay"
    return base + EXT


def export_to(rep, path):
    """Schreibt genau EIN Replay in seinen Umschlag. Gibt (ok, grund) zurück.

    grund: "" bei Erfolg, sonst "invalid" (kaputte Aufnahme) oder "io"
    (Datei nicht schreibbar). Gespeichert wird kompakt - eine Aufnahme ist
    eine Rohdatei, keine zum Handbearbeiten.
    """
    if not _valid(rep):
        return False, "invalid"
    payload = {"format": FORMAT, "v": VERSION, "app": "PyGameZ",
               "exported": time.strftime("%Y-%m-%d %H:%M"),
               "replay": dict(rep)}
    try:
        folder = os.path.dirname(os.path.abspath(path))
        if folder and not os.path.isdir(folder):
            os.makedirs(folder, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))
        return True, ""
    except OSError:
        return False, "io"


def read_file(path):
    """Liest eine geteilte Aufnahme (ohne sie zu speichern).

    Gibt (ok, grund, replay) zurück; grund: "" | "io" | "format".
    Angenommen werden der Umschlag und - für den Notfall - ein "nacktes"
    Replay-dict, wie es in replay.json steht.
    """
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = json.load(f)
    except (OSError, json.JSONDecodeError, ValueError):
        return False, "io", None
    if not isinstance(raw, dict):
        return False, "format", None
    rep = raw.get("replay") if raw.get("format") == FORMAT else raw
    if not _valid(rep):
        return False, "format", None
    return True, "", dict(rep)


def import_from(path, game=None):
    """Liest eine geteilte Aufnahme ein und legt sie ins Archiv.

    'game' ist die Art, die der aufrufende Reiter erwartet - passt sie nicht,
    gibt es "game" (None = jede Art annehmen). Gibt (ok, grund, replay)
    zurück; grund: "" | "io" | "format" | "game" | "full" | "dup".
    """
    ok, why, rep = read_file(path)
    if not ok:
        return False, why, None
    found = rep["game"]
    if game is not None and found != game:
        return False, "game", None
    if is_full(found):
        return False, "full", None
    if is_saved(found, rep["id"]):
        return False, "dup", rep
    rep["id"] = unique_id(rep["id"], found)
    rep["src"] = "file"
    ok, why = save_replay(rep)
    return (True, "", rep) if ok else (False, why, None)


def scene_len(scene):
    """Anzahl Samples einer Szene (flach gespeicherte zählen paarweise)."""
    f = scene.get("f")
    if not isinstance(f, list):
        return 0
    if scene.get("flat"):
        return len(f) // 2
    return len(f)


def duration(rep):
    """Spieldauer eines Replays in Sekunden (Summe aller Samples)."""
    rate = rep.get("rate") or RATE
    total = sum(scene_len(sc) for sc in rep.get("scenes", []))
    return total / float(rate)


def format_duration(seconds):
    """Sekunden -> "1:05" (sprachneutral, für Listen und die Leiste)."""
    seconds = max(0, int(seconds + 0.5))
    return "%d:%02d" % divmod(seconds, 60)


# ---------------------------------------------------------------------------
#  Aufnahme
# ---------------------------------------------------------------------------

class Delta:
    """Kleiner Helfer für Samples, die nur Änderungen enthalten.

    Bowling macht das seit jeher von Hand (Pins stehen nur im Sample, wenn
    sie sich bewegt haben); Billard, Pinball, Snake und Tetris brauchen
    dasselbe für Kugeln, Zellen und Felder. Verwendung::

        d = replay.Delta()
        out = []
        for i, b in enumerate(balls):
            st = (round(b.x, 1), round(b.y, 1), 1 if b.potted else 0)
            if d.push(i, st):
                out.append(i)
                out.extend(st)

    ``reset()`` beim Beginn einer Szene, damit das erste Sample wieder alles
    enthält (eine Szene ist beim Spulen immer der Wiedereinstiegspunkt).
    """

    __slots__ = ("_prev",)

    def __init__(self):
        self._prev = {}

    def reset(self):
        self._prev = {}

    def push(self, key, state):
        """True, wenn sich 'state' seit dem letzten Mal geändert hat."""
        if self._prev.get(key) == state:
            return False
        self._prev[key] = state
        return True


class Recorder:
    """Sammelt die Bahnkurven einer Partie im Speicher.

    Die Spiele rufen nur vier Methoden: ``scene()`` beginnt eine Sequenz,
    ``tick()`` nimmt im festen Raster Samples, ``close()`` beendet sie und
    ``result()`` gibt am Rundenende das fertige Replay-dict zurück.

    Wächst eine Aufnahme über MAX_SAMPLES bzw. MAX_VALUES, hört der Recorder
    auf mitzuschreiben (``self.full``) - das bereits Aufgezeichnete bleibt
    erhalten und wird als "capped" gekennzeichnet, statt eine 20-MB-Datei zu
    erzeugen.
    """

    def __init__(self, game, meta=None):
        self.game = game
        self.meta = dict(meta or {})
        self.layouts = []
        self.scenes = []
        self.samples = 0
        self.values = 0
        self.full = False       # Obergrenze erreicht: nichts Neues mehr
        self.dead = False       # unbrauchbar (nie erreicht, nur Sicherheitsnetz)
        self._scene = None
        self._acc = 0.0

    # ----- Kulissen (Minigolf: die Bahn) --------------------------------

    def layout(self, data):
        """Legt eine Kulisse ab und gibt ihren Index zurück (ohne Dubletten)."""
        if self.dead:
            return 0
        for i, known in enumerate(self.layouts):
            if known == data:
                return i
        self.layouts.append(data)
        return len(self.layouts) - 1

    # ----- Sequenzen -----------------------------------------------------

    def scene(self, flat=False, **info):
        """Beginnt eine Sequenz (Minigolf: ein Schlag, Bowling: ein Wurf).

        Bei Snake und Tetris ist eine Sequenz ein Kapitel: ihre Kopfdaten
        enthalten den vollständigen Zustand, die Samples nur noch Deltas.
        """
        if self.dead or self.full:
            return
        self._scene = dict(info)
        self._scene["flat"] = bool(flat)
        self._scene["f"] = []
        self.scenes.append(self._scene)
        self._acc = STEP          # das erste Sample sofort nehmen

    def set(self, **info):
        """Trägt Kopfdaten in die laufende Sequenz nach (z.B. das Ergebnis)."""
        if self._scene is not None:
            self._scene.update(info)

    def set_last(self, **info):
        """Trägt Kopfdaten in die zuletzt begonnene Sequenz nach.

        Anders als ``set()`` funktioniert das auch, wenn die Sequenz bereits
        geschlossen ist - Minigolf schreibt so das Bahn-Ergebnis noch an den
        letzten Schlag, der die Bahn beendet hat.
        """
        if not self.dead and self.scenes:
            self.scenes[-1].update(info)

    def tick(self, dt, sample_fn):
        """Nimmt im Raster RATE Samples auf (je Frame einmal aufrufen).

        ``sample_fn`` liefert eine Liste/Tupel von Zahlen. Bei einer flachen
        Sequenz werden sie angehängt, sonst als eigenes Sample abgelegt.
        Läuft die Anzeige langsamer als RATE, entstehen mehrere gleiche
        Samples - die Wiedergabe hat dann dasselbe Timing wie das Original.
        """
        if self.dead or self.full or self._scene is None:
            return
        self._acc += dt
        while self._acc >= STEP:
            self._acc -= STEP
            self._emit(sample_fn())

    def _emit(self, values):
        if values is None or self.full:
            return
        sc = self._scene
        if sc["flat"]:
            sc["f"].extend(values)
        else:
            sc["f"].append(list(values))
        self.samples += 1
        self.values += len(values) + 1
        if self.samples > MAX_SAMPLES or self.values > MAX_VALUES:
            self.full = True
            self._scene = None

    def close(self, sample_fn=None, **info):
        """Beendet die laufende Sequenz (mit einem letzten Sample)."""
        if self.dead or self._scene is None:
            return
        if sample_fn is not None:
            self._emit(sample_fn())
        if self._scene is not None:
            self._scene.update(info)
        self._scene = None

    def drop_where(self, **match):
        """Wirft Sequenzen weg, deren Kopfdaten alle Vorgaben erfüllen.

        Gebraucht beim Bahn-Neustart in Minigolf (Taste F): die Schläge der
        abgebrochenen Bahn sollen nicht im Replay landen.
        """
        if self.dead:
            return
        keep = []
        for sc in self.scenes:
            if all(sc.get(k) == v for k, v in match.items()):
                self.samples -= scene_len(sc)
                continue
            keep.append(sc)
        self.scenes = keep
        self._scene = None

    # ----- Abschluss ------------------------------------------------------

    def result(self, title="", sub="", **meta):
        """Baut das fertige Replay-dict (oder None, wenn nichts brauchbar ist)."""
        if self.dead:
            return None
        scenes = [sc for sc in self.scenes if scene_len(sc) > 0]
        if not scenes:
            return None
        self.meta.update(meta)
        if self.full:
            self.meta["capped"] = True
        rep = {"v": VERSION,
               "id": "%s-%s-%d" % (self.game, time.strftime("%Y%m%d%H%M%S"),
                                   len(scenes)),
               "game": self.game,
               "date": time.strftime("%Y-%m-%d %H:%M"),
               "title": title,
               "sub": sub,
               "rate": RATE,
               "meta": self.meta,
               "scenes": scenes}
        if self.layouts:
            rep["layouts"] = self.layouts
        return rep


def recorder(game, settings=None, meta=None):
    """Erzeugt einen Recorder - oder None, wenn Replays abgeschaltet sind."""
    if game not in GAMES:
        return None
    if settings is not None and not is_enabled(settings):
        return None
    return Recorder(game, meta)
