# -*- coding: utf-8 -*-
"""
store.py
========
Zentraler Zugriff auf die einzige Speicherdatei ``mem.json``.

``mem.json`` besteht aus benannten Abschnitten (Sections). Aktuell:

    {
      "_generated": "generated by PyGameZ at ... (YYYY-MM-DD HH:MM:SS)",  # Anlege-Datum
      "mem":        { "lang": "de" },      # Einstellungen der Oberfläche (Sprache ...)
      "highscores": { "snake": 660, ... }  # Bestwerte je Spiel
    }

Jedes Modul liest/schreibt nur seinen eigenen Abschnitt über
``load_section``/``save_section`` - dabei bleibt der Rest der Datei erhalten
(gelesen -> geändert -> komplett zurückgeschrieben). So landen Sprache und
Highscores gemeinsam in EINER Datei.

Alte Formate (getrennte ``highscores.json`` bzw. flaches ``mem.json`` mit
``lang`` auf oberster Ebene) werden beim ersten Laden automatisch in die neue
Struktur übernommen.
"""

import json
import os
import sys
import time

# In einer PyInstaller-.exe (sys.frozen) zeigt __file__ in den temporären
# Entpack-Ordner, der beim Beenden verschwindet - dann neben der .exe speichern.
if getattr(sys, "frozen", False):
    _DIR = os.path.dirname(sys.executable)
else:
    _DIR = os.path.dirname(os.path.abspath(__file__))
_PATH = os.path.join(_DIR, "mem.json")
# Früherer, separater Speicherort der Highscores (nur noch für die Migration).
_LEGACY_HS_PATH = os.path.join(_DIR, "highscores.json")


def _read_raw():
    """Liest mem.json roh (immer ein dict, leer bei Fehler/fehlender Datei)."""
    try:
        with open(_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError, ValueError):
        return {}


def _read_legacy_highscores():
    """Liest eine evtl. noch vorhandene alte highscores.json (leer bei Fehler)."""
    try:
        with open(_LEGACY_HS_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError, ValueError):
        return {}


def _normalize(data):
    """Bringt alte Formate auf die neue {mem, highscores}-Struktur.

    Gibt (normalisiertes_dict, wurde_geändert) zurück.
    """
    changed = False

    # Abschnitt "mem": früher lagen Schlüssel wie "lang" direkt oben.
    if not isinstance(data.get("mem"), dict):
        mem = {}
        for key in ("lang",):
            if key in data:
                mem[key] = data.pop(key)
        data["mem"] = mem
        changed = True

    # Abschnitt "highscores": ggf. aus alter highscores.json übernehmen.
    if not isinstance(data.get("highscores"), dict):
        data["highscores"] = _read_legacy_highscores()
        changed = True

    return data, changed


def load():
    """Liest mem.json als vollständiges dict (mit Abschnitten) und migriert bei Bedarf."""
    data, changed = _normalize(_read_raw())
    if changed:
        save(data)
    return data


def save(data):
    """Schreibt das vollständige dict nach mem.json (Fehler werden ignoriert).

    "_generated" (Anlege-Datum der Datei) steht immer als erster Eintrag;
    ein bereits vorhandener Stempel bleibt erhalten.
    """
    stamp = data.get("_generated")
    if not (isinstance(stamp, str) and stamp):
        stamp = ("generated by PyGameZ at " + time.strftime("%Y-%m-%d %H:%M:%S")
                 + " (YYYY-MM-DD HH:MM:SS)")
    out = {"_generated": stamp}
    out.update((k, v) for k, v in data.items() if k != "_generated")
    try:
        with open(_PATH, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2, ensure_ascii=False)
    except OSError:
        # Schlägt das Speichern fehl (z.B. keine Schreibrechte), läuft das
        # Spiel trotzdem weiter - nur ohne Persistenz.
        pass


def load_section(name):
    """Liefert den Abschnitt 'name' als dict (leer, wenn nicht vorhanden)."""
    section = load().get(name)
    return section if isinstance(section, dict) else {}


def save_section(name, section):
    """Ersetzt den Abschnitt 'name' und schreibt die ganze Datei zurück."""
    data = load()
    data[name] = section
    save(data)
