# -*- coding: utf-8 -*-
"""
ugc.py
======
Eigene Bahnen ("User Generated Content") - Speicher, Prüfung, Austausch.

Gespeichert wird in ``ugc.json`` neben diesem Modul (bei einer mit
pyinstall.bat gebauten .exe: neben der .exe), aufgebaut wie ``replay.json``::

    {
      "_generated": "generated by PyGameZ at ... (YYYY-MM-DD HH:MM:SS)",
      "v": 1,
      "author": "Lama",          # zuletzt benutzter Creator-Name
      "minigolf": [ {map}, {map}, ... ]
    }

Eine Map ist das ganz normale Bahn-Dict aus ``minigolf_gen.make_hole`` plus
Kopfdaten. Das ist Absicht: ``replay.py`` schreibt Bahn-Dicts schon heute
unverändert nach JSON und liest sie zurück in Physik und Rendering - ob die
Zahlen als Tupel oder als Liste ankommen, stört keinen Verbraucher. Deshalb
braucht es hier keinerlei Umwandlung::

    {"v": 1, "id": "tunnelblick", "name": "Tunnelblick", "author": "Lama",
     "created": "2026-08-30 12:00", "edited": "2026-08-30 12:40",
     "w": 100.0, "h": 160.0, "par": 3, "tee": [50, 140], "cup": [50, 26],
     "walls": [...], "tunnels": [...], ...}

Die **id** ist der Schlüssel: eindeutig, klein geschrieben, ohne Leerzeichen
(``ID_CHARS``). Sie ist zugleich der vorgeschlagene Dateiname beim Teilen.
Der **name** ist der Anzeigename und darf alles enthalten.

Teilen
------
Eine exportierte Datei enthält genau EINE Map und trägt die Endung
``.lamapgzmap`` (JSON-Inhalt)::

    {"format": "pygamez.minigolf.map", "v": 1, "app": "PyGameZ",
     "exported": "2026-08-30 12:00", "map": { ... }}

Beim Import wird ``.json`` ebenfalls akzeptiert, und eine schon vergebene id
bekommt automatisch ein ``-2``, ``-3`` ... angehängt.

Wortfilter
----------
Map-Name, Map-id und Creator-Name laufen vor dem Speichern, Exportieren UND
Importieren durch ``swear.is_clean`` (siehe swear.py) - geprüft wird gegen
alle 14 Sprachen. Ein Treffer heißt: wird nicht gespeichert.
"""

import json
import os
import re
import sys
import time

import swear

# In einer PyInstaller-.exe (sys.frozen) zeigt __file__ in den temporären
# Entpack-Ordner, der beim Beenden verschwindet - dann neben der .exe.
if getattr(sys, "frozen", False):
    _DIR = os.path.dirname(sys.executable)
else:
    _DIR = os.path.dirname(os.path.abspath(__file__))
_PATH = os.path.join(_DIR, "ugc.json")

# Format-Version der Dateistruktur (steht in jeder Map und in jedem Export).
VERSION = 1

# Spiele mit eigenen Bahnen = die Unterkategorien in ugc.json.
GAMES = ("minigolf",)

# Höchstens so viele eigene Bahnen je Spiel.
MAX_MAPS = 60

# Endung einer geteilten Bahn. Beim Import wird auch ".json" genommen.
EXT = ".lamapgzmap"
IMPORT_EXTS = (EXT, ".json")

# Kennung im Dateikopf - daran erkennt der Import, dass es eine Bahn ist.
FORMAT = "pygamez.minigolf.map"

# Erlaubte Zeichen einer id: klein, keine Leerzeichen (ausdrückliche Vorgabe).
ID_CHARS = "abcdefghijklmnopqrstuvwxyz0123456789-_"
MAX_ID = 32
MAX_NAME = 28
MAX_AUTHOR = 24

# Grenzen der Bahngröße im Editor (Bahn-Einheiten, siehe minigolf_gen.CW/CH).
MIN_W, MAX_W, STEP_W = 60.0, 160.0, 10.0
MIN_H, MAX_H, STEP_H = 80.0, 240.0, 10.0
MIN_PAR, MAX_PAR = 1, 9


# ---------------------------------------------------------------------------
#  id und Namen
# ---------------------------------------------------------------------------

def slug(text):
    """Macht aus beliebigem Text eine gültige id (leer, wenn nichts bleibt).

    "Mein Tunnel!" -> "mein-tunnel". Umlaute werden ausgeschrieben, alles
    andere Unerlaubte wird zu "-", Mehrfach-Striche fallen zusammen.
    """
    if not isinstance(text, str):
        return ""
    out = text.strip().lower()
    for src, dst in (("ä", "ae"), ("ö", "oe"), ("ü", "ue"), ("ß", "ss"),
                     ("å", "a"), ("æ", "ae"), ("ø", "oe")):
        out = out.replace(src, dst)
    out = "".join(c if c in ID_CHARS else "-" for c in out)
    out = re.sub(r"-+", "-", out).strip("-_")
    return out[:MAX_ID]


def valid_id(text):
    """True, wenn 'text' als id taugt (nicht leer, nur erlaubte Zeichen)."""
    return (isinstance(text, str) and 0 < len(text) <= MAX_ID
            and all(c in ID_CHARS for c in text))


def unique_id(wanted, game="minigolf", ignore=None):
    """Freie id: hängt -2, -3 ... an, solange 'wanted' schon vergeben ist.

    'ignore' ist die id der Map, die gerade bearbeitet wird - sie blockiert
    sich nicht selbst.
    """
    base = slug(wanted) or "map"
    taken = {m.get("id") for m in load_maps(game) if m.get("id") != ignore}
    if base not in taken:
        return base
    for n in range(2, 1000):
        cand = "%s-%d" % (base[:MAX_ID - len(str(n)) - 1], n)
        if cand not in taken:
            return cand
    return base


# ---------------------------------------------------------------------------
#  Datei lesen/schreiben
# ---------------------------------------------------------------------------

def _read_raw():
    """Liest ugc.json roh (immer ein dict, leer bei Fehler/ohne Datei)."""
    try:
        with open(_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError, ValueError):
        return {}


def _write_raw(data):
    """Schreibt die ganze Datei zurück (Fehler werden bewusst geschluckt).

    Anders als replay.json wird hier MIT Einrückung gespeichert: eigene
    Bahnen darf man ruhig von Hand anschauen und anpassen.
    """
    stamp = data.get("_generated")
    if not (isinstance(stamp, str) and stamp):
        stamp = ("generated by PyGameZ at " + time.strftime("%Y-%m-%d %H:%M:%S")
                 + " (YYYY-MM-DD HH:MM:SS)")
    out = {"_generated": stamp, "v": VERSION}
    if isinstance(data.get("author"), str) and data["author"]:
        out["author"] = data["author"]
    for key in GAMES:
        items = data.get(key)
        if isinstance(items, list) and items:
            out[key] = items
    try:
        with open(_PATH, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2, ensure_ascii=False)
        return True
    except OSError:
        # Ohne Schreibrechte läuft alles weiter - nur eben ohne Sammlung.
        return False


def _valid(m):
    """Grobprüfung einer geladenen Map (beschädigte werden übersprungen)."""
    return (isinstance(m, dict) and valid_id(m.get("id"))
            and isinstance(m.get("name"), str) and m["name"].strip()
            and isinstance(m.get("tee"), (list, tuple))
            and isinstance(m.get("cup"), (list, tuple)))


# ---------------------------------------------------------------------------
#  Sammlung
# ---------------------------------------------------------------------------

def load_maps(game="minigolf"):
    """Alle eigenen Bahnen eines Spiels (neueste zuerst, wie gespeichert)."""
    items = _read_raw().get(game)
    if not isinstance(items, list):
        return []
    from games import minigolf_gen as gen
    return [gen.normalize(m) for m in items if _valid(m)]


def get(map_id, game="minigolf"):
    """Eine Bahn über ihre id (oder None)."""
    for m in load_maps(game):
        if m.get("id") == map_id:
            return m
    return None


def count(game="minigolf"):
    return len(load_maps(game))


def is_full(game="minigolf"):
    return count(game) >= MAX_MAPS


def save_map(m, game="minigolf"):
    """Speichert eine Bahn dauerhaft. Gibt (ok, grund) zurück.

    grund ist "" bei Erfolg, sonst "invalid" (Pflichtfelder fehlen), "id"
    (unbrauchbare id), "swear" (Wortfilter), "full" (Sammlung voll) oder
    "io" (Datei nicht schreibbar). Eine vorhandene Bahn gleicher id wird
    ersetzt - das ist der normale Fall beim Weiterbearbeiten.
    """
    if not _valid(m):
        return False, "invalid"
    if not valid_id(m.get("id")):
        return False, "id"
    if not swear.all_clean(m.get("name"), m.get("id"), m.get("author")):
        return False, "swear"
    data = _read_raw()
    items = data.get(game)
    if not isinstance(items, list):
        items = []
    items = [x for x in items if _valid(x) and x.get("id") != m["id"]]
    if len(items) >= MAX_MAPS:
        return False, "full"
    m = dict(m)
    m["v"] = VERSION
    m["edited"] = time.strftime("%Y-%m-%d %H:%M")
    m.setdefault("created", m["edited"])
    items.append(m)
    data[game] = items
    return (True, "") if _write_raw(data) else (False, "io")


def delete_map(map_id, game="minigolf"):
    """Löscht eine Bahn. True, wenn sie da war und die Datei geschrieben wurde."""
    data = _read_raw()
    items = data.get(game)
    if not isinstance(items, list):
        return False
    keep = [x for x in items if x.get("id") != map_id]
    if len(keep) == len(items):
        return False
    data[game] = keep
    return _write_raw(data)


# ---------------------------------------------------------------------------
#  Creator-Name (fürs nächste Mal merken)
# ---------------------------------------------------------------------------

def last_author():
    """Zuletzt benutzter Creator-Name (leer, wenn noch keiner gesetzt ist)."""
    a = _read_raw().get("author")
    return a if isinstance(a, str) else ""


def set_last_author(name):
    """Merkt sich den Creator-Namen (nur, wenn er den Wortfilter passiert)."""
    if not isinstance(name, str) or not name.strip():
        return False
    name = name.strip()[:MAX_AUTHOR]
    if not swear.is_clean(name):
        return False
    data = _read_raw()
    data["author"] = name
    return _write_raw(data)


# ---------------------------------------------------------------------------
#  Bahn <-> Map
# ---------------------------------------------------------------------------

def to_hole(m):
    """Reines Bahn-Dict aus einer Map (Kopfdaten wie id/name bleiben draußen).

    Das Ergebnis geht unverändert in Physik, Rendering und Replay - genau
    wie eine eingebaute oder erzeugte Bahn.
    """
    from games import minigolf_gen as gen
    m = gen.normalize(dict(m))
    hole = {"par": int(m.get("par", 3)),
            "tee": tuple(m["tee"][:2]), "cup": tuple(m["cup"][:2]),
            "w": m["w"], "h": m["h"]}
    for key in gen.HOLE_LISTS:
        hole[key] = [tuple(item) for item in m[key]]
    return hole


def new_map(name="", map_id="", author="", hole=None):
    """Baut eine frische Map (leere Bahn, wenn 'hole' fehlt)."""
    from games import minigolf_gen as gen
    hole = gen.normalize(dict(hole) if hole else
                         gen.make_hole(3, (gen.CW / 2, gen.CH - 16),
                                       (gen.CW / 2, 22)))
    now = time.strftime("%Y-%m-%d %H:%M")
    m = {"v": VERSION, "id": map_id, "name": name, "author": author,
         "created": now, "edited": now}
    m.update(hole)
    return m


# ---------------------------------------------------------------------------
#  Teilen: Export / Import
# ---------------------------------------------------------------------------

def default_filename(m):
    """Vorgeschlagener Dateiname beim Teilen: die id der Bahn plus Endung."""
    return (m.get("id") or "map") + EXT


def export_to(m, path):
    """Schreibt genau EINE Bahn als .lamapgzmap. Gibt (ok, grund) zurück.

    grund: "" | "invalid" | "swear" | "io".
    """
    if not _valid(m):
        return False, "invalid"
    if not swear.all_clean(m.get("name"), m.get("id"), m.get("author")):
        return False, "swear"
    payload = {"format": FORMAT, "v": VERSION, "app": "PyGameZ",
               "exported": time.strftime("%Y-%m-%d %H:%M"), "map": dict(m)}
    try:
        folder = os.path.dirname(os.path.abspath(path))
        if folder and not os.path.isdir(folder):
            os.makedirs(folder, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
        return True, ""
    except OSError:
        return False, "io"


def import_from(path, game="minigolf"):
    """Liest eine geteilte Bahn ein. Gibt (ok, grund, map) zurück.

    Die Bahn wird direkt gespeichert; eine schon vergebene id bekommt
    automatisch ein "-2" (die zurückgegebene Map trägt dann die neue id).
    grund: "" | "io" | "format" | "swear" | "full" | "invalid" | "id".
    """
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = json.load(f)
    except (OSError, json.JSONDecodeError, ValueError):
        return False, "io", None
    if not isinstance(raw, dict):
        return False, "format", None
    # Entweder der volle Umschlag - oder notfalls eine nackte Map.
    m = raw.get("map") if raw.get("format") == FORMAT else raw
    if not isinstance(m, dict):
        return False, "format", None
    from games import minigolf_gen as gen
    m = dict(m)
    m["id"] = slug(m.get("id") or m.get("name") or "")
    m["name"] = (m.get("name") or m["id"] or "").strip()[:MAX_NAME]
    if isinstance(m.get("author"), str):
        m["author"] = m["author"].strip()[:MAX_AUTHOR]
    gen.normalize(m)
    if not _valid(m):
        return False, "format", None
    if not swear.all_clean(m.get("name"), m.get("id"), m.get("author")):
        return False, "swear", None
    if is_full(game):
        return False, "full", None
    m["id"] = unique_id(m["id"], game)
    ok, reason = save_map(m, game)
    return (True, "", m) if ok else (False, reason, None)
