# -*- coding: utf-8 -*-
"""
ugc.py
======
Eigene Inhalte ("User Generated Content") - Speicher, Prüfung, Austausch.

Heute gibt es zwei Arten: eigene **Minigolf-Bahnen** und eigene
**Geometry-Dash-Level**. Jede Art steht in der Registry ``KINDS`` mit ihrem
Dateiformat, ihrer Endung, ihrer Prüf- und Aufräumfunktion und ihrer
Höchstzahl. Alle Funktionen nehmen die Art als ``game`` - ohne Angabe ist es
wie früher Minigolf, bestehender Code läuft also unverändert.

Gespeichert wird in ``ugc.json`` neben diesem Modul (bei einer mit
pyinstall.bat gebauten .exe: neben der .exe), aufgebaut wie ``replay.json``::

    {
      "_generated": "generated by PyGameZ at ... (YYYY-MM-DD HH:MM:SS)",
      "v": 1,
      "author": "Lama",          # zuletzt benutzter Creator-Name
      "minigolf": [ {map}, {map}, ... ],
      "geodash": [ {level}, ... ]
    }

Eine Minigolf-Map ist das ganz normale Bahn-Dict aus
``minigolf_gen.make_hole`` plus Kopfdaten. Das ist Absicht: ``replay.py``
schreibt Bahn-Dicts schon heute unverändert nach JSON und liest sie zurück in
Physik und Rendering - ob die Zahlen als Tupel oder als Liste ankommen, stört
keinen Verbraucher. Deshalb braucht es hier keinerlei Umwandlung::

    {"v": 1, "id": "tunnelblick", "name": "Tunnelblick", "author": "Lama",
     "created": "2026-08-30 12:00", "edited": "2026-08-30 12:40",
     "w": 100.0, "h": 160.0, "par": 3, "tee": [50, 140], "cup": [50, 26],
     "walls": [...], "tunnels": [...], ...}

Ein Geometry-Dash-Level ist das Level-Dict aus ``geodash_core`` (Objekte,
Starttempo, Farben, Musikstil) plus dieselben Kopfdaten und - sobald der
Ersteller es selbst geschafft hat - ``verified`` (Prüfsumme des Inhalts).

Die **id** ist der Schlüssel: eindeutig je Art, klein geschrieben, ohne
Leerzeichen (``ID_CHARS``). Sie ist zugleich der vorgeschlagene Dateiname beim
Teilen. Der **name** ist der Anzeigename und darf alles enthalten.

Teilen
------
Eine exportierte Datei enthält genau EINEN Inhalt im Umschlag seiner Art::

    .lamapgzmap    {"format": "pygamez.minigolf.map", "v": 1, "app": "PyGameZ",
                    "exported": "2026-08-30 12:00", "map": { ... }}
    .lamapgzlevel  {"format": "pygamez.geodash.level", ..., "level": { ... }}

Beim Import wird ``.json`` ebenfalls akzeptiert. Welche Art drinsteckt,
entscheidet das ``format`` im Umschlag; eine Minigolf-Bahn darf auch "nackt"
(ohne Umschlag) kommen. Passt die Art nicht zum Dialog, aus dem importiert
wird, gibt es "format". Eine schon vergebene id bekommt automatisch ein
``-2``, ``-3`` ... angehängt.

Wortfilter
----------
Name, id und Creator-Name laufen vor dem Speichern, Exportieren UND
Importieren durch ``swear.is_clean`` (siehe swear.py) - geprüft wird gegen
alle 14 Sprachen. Ein Treffer heißt: wird nicht gespeichert.
"""

import json
import os
import re
import sys
import time

import swear

# In einer PyInstaller-.exe (sys.frozen) zeigt __file__ in den temporären
# Entpack-Ordner, der beim Beenden verschwindet - dann neben der .exe.
if getattr(sys, "frozen", False):
    _DIR = os.path.dirname(sys.executable)
else:
    _DIR = os.path.dirname(os.path.abspath(__file__))
_PATH = os.path.join(_DIR, "ugc.json")

# Format-Version der Dateistruktur (steht in jedem Inhalt und jedem Export).
VERSION = 1

# Höchstens so viele eigene Bahnen je Spiel (Minigolf - siehe KINDS).
MAX_MAPS = 60

# Endung einer geteilten Bahn. Beim Import wird auch ".json" genommen.
EXT = ".lamapgzmap"
IMPORT_EXTS = (EXT, ".json")

# Kennung im Dateikopf - daran erkennt der Import, dass es eine Bahn ist.
FORMAT = "pygamez.minigolf.map"

# Erlaubte Zeichen einer id: klein, keine Leerzeichen (ausdrückliche Vorgabe).
ID_CHARS = "abcdefghijklmnopqrstuvwxyz0123456789-_"
MAX_ID = 32
MAX_NAME = 28
MAX_AUTHOR = 24

# Grenzen der Bahngröße im Editor (Bahn-Einheiten, siehe minigolf_gen.CW/CH).
MIN_W, MAX_W, STEP_W = 60.0, 160.0, 10.0
MIN_H, MAX_H, STEP_H = 80.0, 240.0, 10.0
MIN_PAR, MAX_PAR = 1, 9


# ---------------------------------------------------------------------------
#  Registry der Arten
# ---------------------------------------------------------------------------

def _head_ok(m):
    return (isinstance(m, dict) and valid_id(m.get("id"))
            and isinstance(m.get("name"), str) and bool(m["name"].strip()))


def _golf_valid(m):
    """Grobprüfung einer geladenen Map (beschädigte werden übersprungen)."""
    return (_head_ok(m)
            and isinstance(m.get("tee"), (list, tuple))
            and isinstance(m.get("cup"), (list, tuple)))


def _golf_normalize(m):
    from games import minigolf_gen as gen
    return gen.normalize(m)


def _gd_valid(m):
    return _head_ok(m) and isinstance(m.get("objects"), (list, tuple))


def _gd_normalize(m):
    from games import geodash_core as core
    return core.normalize_level(m)


# game -> Eigenschaften. "key" ist der Schlüssel des Inhalts im Umschlag.
KINDS = {
    "minigolf": {"format": FORMAT, "ext": EXT, "key": "map",
                 "validate": _golf_valid, "normalize": _golf_normalize,
                 "max_items": MAX_MAPS, "naked": True},
    "geodash": {"format": "pygamez.geodash.level", "ext": ".lamapgzlevel",
                "key": "level", "validate": _gd_valid,
                "normalize": _gd_normalize, "max_items": 60, "naked": False},
}

# Spiele mit eigenen Inhalten = die Unterkategorien in ugc.json.
GAMES = tuple(KINDS)


def kind(game):
    """Eigenschaften einer Art (unbekannte Arten gelten als Minigolf)."""
    return KINDS.get(game, KINDS["minigolf"])


def ext(game="minigolf"):
    """Datei-Endung beim Teilen (".lamapgzmap", ".lamapgzlevel")."""
    return kind(game)["ext"]


def import_exts(game="minigolf"):
    """Endungen, die der Import-Dialog anbietet."""
    return (kind(game)["ext"], ".json")


def max_items(game="minigolf"):
    return kind(game)["max_items"]


# ---------------------------------------------------------------------------
#  id und Namen
# ---------------------------------------------------------------------------

def slug(text):
    """Macht aus beliebigem Text eine gültige id (leer, wenn nichts bleibt).

    "Mein Tunnel!" -> "mein-tunnel". Umlaute werden ausgeschrieben, alles
    andere Unerlaubte wird zu "-", Mehrfach-Striche fallen zusammen.
    """
    if not isinstance(text, str):
        return ""
    out = text.strip().lower()
    for src, dst in (("ä", "ae"), ("ö", "oe"), ("ü", "ue"), ("ß", "ss"),
                     ("å", "a"), ("æ", "ae"), ("ø", "oe")):
        out = out.replace(src, dst)
    out = "".join(c if c in ID_CHARS else "-" for c in out)
    out = re.sub(r"-+", "-", out).strip("-_")
    return out[:MAX_ID]


def valid_id(text):
    """True, wenn 'text' als id taugt (nicht leer, nur erlaubte Zeichen)."""
    return (isinstance(text, str) and 0 < len(text) <= MAX_ID
            and all(c in ID_CHARS for c in text))


def unique_id(wanted, game="minigolf", ignore=None):
    """Freie id: hängt -2, -3 ... an, solange 'wanted' schon vergeben ist.

    'ignore' ist die id des Inhalts, der gerade bearbeitet wird - er
    blockiert sich nicht selbst.
    """
    base = slug(wanted) or ("level" if game == "geodash" else "map")
    taken = {m.get("id") for m in load_maps(game) if m.get("id") != ignore}
    if base not in taken:
        return base
    for n in range(2, 1000):
        cand = "%s-%d" % (base[:MAX_ID - len(str(n)) - 1], n)
        if cand not in taken:
            return cand
    return base


# ---------------------------------------------------------------------------
#  Datei lesen/schreiben
# ---------------------------------------------------------------------------

def _read_raw():
    """Liest ugc.json roh (immer ein dict, leer bei Fehler/ohne Datei)."""
    try:
        with open(_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError, ValueError):
        return {}


def _write_raw(data):
    """Schreibt die ganze Datei zurück (Fehler werden bewusst geschluckt).

    Anders als replay.json wird hier MIT Einrückung gespeichert: eigene
    Bahnen darf man ruhig von Hand anschauen und anpassen. Übernommen werden
    ALLE Listen - auch die einer Art, die diese Programmversion noch nicht
    kennt (eine neuere Version darf die Datei nicht leerräumen lassen).
    """
    stamp = data.get("_generated")
    if not (isinstance(stamp, str) and stamp):
        stamp = ("generated by PyGameZ at " + time.strftime("%Y-%m-%d %H:%M:%S")
                 + " (YYYY-MM-DD HH:MM:SS)")
    out = {"_generated": stamp, "v": VERSION}
    if isinstance(data.get("author"), str) and data["author"]:
        out["author"] = data["author"]
    keys = [k for k in GAMES] + sorted(k for k in data if k not in KINDS)
    for key in keys:
        if key in ("_generated", "v", "author"):
            continue
        items = data.get(key)
        if isinstance(items, list) and items:
            out[key] = items
    try:
        with open(_PATH, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2, ensure_ascii=False)
        return True
    except OSError:
        # Ohne Schreibrechte läuft alles weiter - nur eben ohne Sammlung.
        return False


def _valid(m, game="minigolf"):
    """Grobprüfung eines geladenen Inhalts (beschädigte werden übersprungen)."""
    return bool(kind(game)["validate"](m))


# ---------------------------------------------------------------------------
#  Sammlung
# ---------------------------------------------------------------------------

def load_maps(game="minigolf"):
    """Alle eigenen Inhalte einer Art (neueste zuerst, wie gespeichert)."""
    items = _read_raw().get(game)
    if not isinstance(items, list):
        return []
    k = kind(game)
    return [k["normalize"](m) for m in items if k["validate"](m)]


def get(map_id, game="minigolf"):
    """Ein Inhalt über seine id (oder None)."""
    for m in load_maps(game):
        if m.get("id") == map_id:
            return m
    return None


def count(game="minigolf"):
    return len(load_maps(game))


def is_full(game="minigolf"):
    return count(game) >= max_items(game)


def save_map(m, game="minigolf"):
    """Speichert einen Inhalt dauerhaft. Gibt (ok, grund) zurück.

    grund ist "" bei Erfolg, sonst "invalid" (Pflichtfelder fehlen), "id"
    (unbrauchbare id), "swear" (Wortfilter), "full" (Sammlung voll) oder
    "io" (Datei nicht schreibbar). Ein vorhandener Inhalt gleicher id wird
    ersetzt - das ist der normale Fall beim Weiterbearbeiten.
    """
    if not _valid(m, game):
        return False, "invalid"
    if not valid_id(m.get("id")):
        return False, "id"
    if not swear.all_clean(m.get("name"), m.get("id"), m.get("author")):
        return False, "swear"
    data = _read_raw()
    items = data.get(game)
    if not isinstance(items, list):
        items = []
    items = [x for x in items if _valid(x, game) and x.get("id") != m["id"]]
    if len(items) >= max_items(game):
        return False, "full"
    m = dict(m)
    m["v"] = VERSION
    m["edited"] = time.strftime("%Y-%m-%d %H:%M")
    m.setdefault("created", m["edited"])
    items.append(m)
    data[game] = items
    return (True, "") if _write_raw(data) else (False, "io")


def delete_map(map_id, game="minigolf"):
    """Löscht einen Inhalt. True, wenn er da war und die Datei geschrieben wurde."""
    data = _read_raw()
    items = data.get(game)
    if not isinstance(items, list):
        return False
    keep = [x for x in items if not isinstance(x, dict) or x.get("id") != map_id]
    if len(keep) == len(items):
        return False
    data[game] = keep
    return _write_raw(data)


# ---------------------------------------------------------------------------
#  Creator-Name (fürs nächste Mal merken)
# ---------------------------------------------------------------------------

def last_author():
    """Zuletzt benutzter Creator-Name (leer, wenn noch keiner gesetzt ist)."""
    a = _read_raw().get("author")
    return a if isinstance(a, str) else ""


def set_last_author(name):
    """Merkt sich den Creator-Namen (nur, wenn er den Wortfilter passiert)."""
    if not isinstance(name, str) or not name.strip():
        return False
    name = name.strip()[:MAX_AUTHOR]
    if not swear.is_clean(name):
        return False
    data = _read_raw()
    data["author"] = name
    return _write_raw(data)


# ---------------------------------------------------------------------------
#  Bahn <-> Map (nur Minigolf)
# ---------------------------------------------------------------------------

def to_hole(m):
    """Reines Bahn-Dict aus einer Map (Kopfdaten wie id/name bleiben draußen).

    Das Ergebnis geht unverändert in Physik, Rendering und Replay - genau
    wie eine eingebaute oder erzeugte Bahn.
    """
    from games import minigolf_gen as gen
    m = gen.normalize(dict(m))
    hole = {"par": int(m.get("par", 3)),
            "tee": tuple(m["tee"][:2]), "cup": tuple(m["cup"][:2]),
            "w": m["w"], "h": m["h"]}
    for key in gen.HOLE_LISTS:
        hole[key] = [tuple(item) for item in m[key]]
    return hole


def new_map(name="", map_id="", author="", hole=None):
    """Baut eine frische Map (leere Bahn, wenn 'hole' fehlt)."""
    from games import minigolf_gen as gen
    hole = gen.normalize(dict(hole) if hole else
                         gen.make_hole(3, (gen.CW / 2, gen.CH - 16),
                                       (gen.CW / 2, 22)))
    now = time.strftime("%Y-%m-%d %H:%M")
    m = {"v": VERSION, "id": map_id, "name": name, "author": author,
         "created": now, "edited": now}
    m.update(hole)
    return m


# ---------------------------------------------------------------------------
#  Teilen: Export / Import
# ---------------------------------------------------------------------------

def default_filename(m, game="minigolf"):
    """Vorgeschlagener Dateiname beim Teilen: die id plus Endung."""
    fallback = "level" if game == "geodash" else "map"
    return (m.get("id") or fallback) + ext(game)


def export_to(m, path, game="minigolf"):
    """Schreibt genau EINEN Inhalt in seinen Umschlag. Gibt (ok, grund) zurück.

    grund: "" | "invalid" | "swear" | "io".
    """
    if not _valid(m, game):
        return False, "invalid"
    if not swear.all_clean(m.get("name"), m.get("id"), m.get("author")):
        return False, "swear"
    k = kind(game)
    payload = {"format": k["format"], "v": VERSION, "app": "PyGameZ",
               "exported": time.strftime("%Y-%m-%d %H:%M"), k["key"]: dict(m)}
    try:
        folder = os.path.dirname(os.path.abspath(path))
        if folder and not os.path.isdir(folder):
            os.makedirs(folder, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
        return True, ""
    except OSError:
        return False, "io"


def detect_game(raw):
    """Art eines Umschlags anhand seines "format" (oder None)."""
    if isinstance(raw, dict):
        for game, k in KINDS.items():
            if raw.get("format") == k["format"]:
                return game
    return None


def import_from(path, game="minigolf"):
    """Liest einen geteilten Inhalt ein. Gibt (ok, grund, inhalt) zurück.

    Die Art bestimmt der Umschlag ("format"). 'game' ist die Art, die der
    aufrufende Dialog erwartet - passt sie nicht, gibt es "format" (None =
    jede Art annehmen). Eine nackte Map ohne Umschlag geht nur bei Minigolf.
    Der Inhalt wird direkt gespeichert; eine schon vergebene id bekommt
    automatisch ein "-2" (der zurückgegebene Inhalt trägt dann die neue id).
    grund: "" | "io" | "format" | "swear" | "full" | "invalid" | "id".
    """
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = json.load(f)
    except (OSError, json.JSONDecodeError, ValueError):
        return False, "io", None
    if not isinstance(raw, dict):
        return False, "format", None
    found = detect_game(raw)
    if found is None:
        # Kein bekannter Umschlag: notfalls eine nackte Minigolf-Map.
        if game not in (None, "minigolf"):
            return False, "format", None
        found, m = "minigolf", raw
    else:
        if game is not None and found != game:
            return False, "format", None
        m = raw.get(kind(found)["key"])
    if not isinstance(m, dict):
        return False, "format", None
    k = kind(found)
    m = dict(m)
    m["id"] = slug(m.get("id") or m.get("name") or "")
    m["name"] = (m.get("name") or m["id"] or "").strip()[:MAX_NAME]
    if isinstance(m.get("author"), str):
        m["author"] = m["author"].strip()[:MAX_AUTHOR]
    m = k["normalize"](m) or m
    if not k["validate"](m):
        return False, "format", None
    if not swear.all_clean(m.get("name"), m.get("id"), m.get("author")):
        return False, "swear", None
    if is_full(found):
        return False, "full", None
    m["id"] = unique_id(m["id"], found)
    ok, reason = save_map(m, found)
    return (True, "", m) if ok else (False, reason, None)
