/*
 * manifest.js - Spiele-Reihenfolge (wie games/__init__.py ALL_GAMES) und die
 * Skriptdateien je Spiel. app.js lädt die Dateien der Reihe nach; eine Datei,
 * die von mehreren Spielen genutzt wird (z.B. cards.js), wird nur einmal geladen.
 */
window.PG_MANIFEST = [
  { id: "SnakeGame", files: ["js/games/snake.js"] },
  { id: "PongGame", files: ["js/games/pong.js"] },
  { id: "AirHockeyGame", files: ["js/games/airhockey.js"] },
  { id: "TicTacToeGame", files: ["js/games/tictactoe.js"] },
  { id: "BreakoutGame", files: ["js/games/breakout.js"] },
  { id: "TetrisGame", files: ["js/games/tetris.js"] },
  { id: "InvadersGame", files: ["js/games/invaders.js"] },
  { id: "AsteroidsGame", files: ["js/games/asteroids.js"] },
  { id: "PacmanGame", files: ["js/games/pacman.js"] },
  { id: "FlappyGame", files: ["js/games/flappy.js"] },
  { id: "DoodleGame", files: ["js/games/doodle.js"] },
  { id: "Game2048", files: ["js/games/game2048.js"] },
  { id: "MinesweeperGame", files: ["js/games/minesweeper.js"] },
  { id: "SudokuGame", files: ["js/games/sudoku_gen.js", "js/games/sudoku.js"] },
  { id: "FroggerGame", files: ["js/games/frogger.js"] },
  { id: "MemoryGame", files: ["js/games/memory.js"] },
  { id: "SolitaireGame", files: ["js/games/cards.js", "js/games/solitaire.js"] },
  { id: "AimTrainerGame", files: ["js/games/aimtrainer.js"] },
  { id: "ConnectFourGame", files: ["js/games/connect4.js"] },
  { id: "TankDuelGame", files: ["js/games/tanks.js"] },
  { id: "BlackjackGame", files: ["js/games/cards.js", "js/games/blackjack.js"] },
  { id: "TunnelRacerGame", files: ["js/games/tunnelracer.js"] },
  { id: "LabyrinthGame", files: ["js/games/maze_gen.js", "js/games/labyrinth.js"] },
  { id: "ReversiGame", files: ["js/games/reversi.js"] },
  { id: "KniffelGame", files: ["js/games/kniffel.js"] },
  { id: "WordleGame", files: ["js/games/wordle_words.js", "js/games/wordle.js"] },
  { id: "TRexRunnerGame", files: ["js/games/trexrunner.js"] },
  { id: "DameGame", files: ["js/games/dame.js"] },
  { id: "PokerGame", files: ["js/games/cards.js", "js/games/poker.js"] },
  { id: "ChessGame", files: ["js/games/chess.js"] },
  { id: "MuehleGame", files: ["js/games/muehle.js"] },
  { id: "SimonGame", files: ["js/games/simon.js"] },
  { id: "BilliardGame", files: ["js/games/billiard.js"] },
  { id: "SlidingPuzzleGame", files: ["js/games/slidepuzzle.js"] },
  { id: "MastermindGame", files: ["js/games/mastermind.js"] },
  { id: "BubbleShooterGame", files: ["js/games/bubbleshooter.js"] },
  { id: "HangmanGame", files: ["js/games/hangman_words.js", "js/games/hangman.js"] },
  { id: "BlockJumpGame", files: ["js/games/blockjump.js"] },
  { id: "LamaTowerDefenseGame", files: ["js/games/lamatowerdefense.js"] },
  { id: "MiniGolfGame", files: ["js/games/minigolf_gen.js", "js/games/minigolf_draw.js", "js/games/minigolf_edit.js", "js/games/minigolf.js"] },
  { id: "PinballGame", files: ["js/games/pinball.js"] },
  { id: "BowlingGame", files: ["js/games/bowling.js"] },
];
